export const TEST_ACTION = 'TEST_ACTION';
export const TEST_ACTION_1 = 'TEST_ACTION_1';

export const USER_REGISTRATION = 'USER_REGISTRATION';
export const USER_LOGIN = 'USER_LOGIN';

export const PAGE_TOGGLE_LOADING_OVERLAY = 'PAGE_TOGGLE_LOADING_OVERLAY';
