export const TEST_ACTION = 'TEST_ACTION';
export const TEST_ACTION_1 = 'TEST_ACTION_1';

export const USER_REGISTRATION = 'USER_REGISTRATION';
export const USER_LOGIN = 'USER_LOGIN';

export const PAGE_TOGGLE_LOADING_OVERLAY = 'PAGE_TOGGLE_LOADING_OVERLAY';

export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export const POST_PRODUCT_WATCHER = 'POST_PRODUCT_WATCHER';
export const GET_LIST_PRODUCT_WATCHER = 'GET_LIST_PRODUCT_WATCHER';

export const GET_LIST_MESSAGE = 'GET_LIST_MESSAGE';
